export const extensionsData = [
  {
    id: 1,
    name: "DevLens",
    text: "Quickly inspect page layouts and visualize element boundaries.",
    img: "../assets/images/logo-devlens.svg",
    active: true,
  },
  {
    id: 2,
    name: "StyleSpy",
    text: "Instantly analyze and copy CSS from any webpage element.",
    img: "../assets/images/logo-style-spy.svg",
    active: true,
  },
  {
    id: 3,
    name: "SpeedBoost",
    text: "Optimizes browser resource accelerate page loading.",
    img: "../assets/images/logo-speed-boost.svg",
    active: true,
  },
  {
    id: 4,
    name: "JSONWizard",
    text: "Formats, validates, and prettifies JSON responses in-browser.",
    img: "../assets/images/logo-json-wizard.svg",
    active: true,
  },
  {
    id: 5,
    name: "TabMaster Pro",
    text: "Organizes browser tabs into groups and sessions.",
    img: "../assets/images/logo-tab-master-pro.svg",
    active: true,
  },
  {
    id: 6,
    name: "ViewportBuddy",
    text: "Simulates various screen resolutions directly within the browser.",
    img: "../assets/images/logo-viewport-buddy.svg",
    active: true,
  },
  {
    id: 7,
    name: "Markup Notes",
    text: "Enables annotation and notes directly onto webpages for collaborative debugging.",
    img: "../assets/images/logo-markup-notes.svg",
    active: true,
  },
  {
    id: 8,
    name: "GridGuides",
    text: "Overlay customizable grids and alignment guides on any webpage.",
    img: "../assets/images/logo-grid-guides.svg",
    active: true,
  },
  {
    id: 9,
    name: "Palette Picker",
    text: "Instantly extract color palettes from any webpage.",
    img: "../assets/images/logo-palette-picker.svg",
    active: true,
  },
  {
    id: 10,
    name: "LinkChecker",
    text: "Scans and highlights broken links on any page.",
    img: "../assets/images/logo-link-checker.svg",
    active: true,
  },
  {
    id: 11,
    name: "DOM Snapshot",
    text: "Capture and export DOM structures quickly",
    img: "../assets/images/logo-dom-snapshot.svg",
    active: true,
  },
  {
    id: 12,
    name: "ConsolePlus",
    text: "Enhanced developer console with advanced filtering and logging",
    img: "../assets/images/logo-console-plus.svg",
    active: true,
  },
];
